package com.capstone.todo.web.api;

import com.capstone.todo.web.filter.CorrelationIdFilter;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.testng.Assert;

import java.util.UUID;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest(controllers = GlobalExceptionHandlerTest.ValidationController.class)
@Import({GlobalExceptionHandler.class, CorrelationIdFilter.class})
class GlobalExceptionHandlerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @WithMockUser
    @org.testng.annotations.Test
    void validationError_withoutHeader_returns400_andGeneratedCorrelationId_andDetails() throws Exception {
        mockMvc.perform(post("/api/test/validate")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{}"))
            .andExpect(status().isBadRequest())
            .andExpect(header().exists(CorrelationIdFilter.CORRELATION_ID_HEADER))
            .andExpect(result -> {
                String headerCorrelationId = result.getResponse().getHeader(CorrelationIdFilter.CORRELATION_ID_HEADER);
                Assert.assertNotNull(headerCorrelationId, "X-Correlation-ID response header must be present");

                // Ensure it is UUID-shaped when generated by the server.
                UUID.fromString(headerCorrelationId);

                JsonNode root = objectMapper.readTree(result.getResponse().getContentAsString());
                String bodyCorrelationId = root.path("error").path("correlationId").asText();
                Assert.assertNotNull(bodyCorrelationId, "Body correlationId must be present");

                UUID.fromString(bodyCorrelationId);

                Assert.assertEquals(bodyCorrelationId, headerCorrelationId,
                    "Body correlationId does not match response header correlation id");
            })
            .andExpect(jsonPath("$.error.code").value("VALIDATION_ERROR"))
            .andExpect(jsonPath("$.error.details").isArray())
            .andExpect(jsonPath("$.error.correlationId").isNotEmpty());
    }

    @WithMockUser
    @org.testng.annotations.Test
    void validationError_withHeader_returns400_andSameCorrelationId() throws Exception {
        mockMvc.perform(post("/api/test/validate")
                .header(CorrelationIdFilter.CORRELATION_ID_HEADER, "client-uuid")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{}"))
            .andExpect(status().isBadRequest())
            .andExpect(header().string(CorrelationIdFilter.CORRELATION_ID_HEADER, "client-uuid"))
            .andExpect(jsonPath("$.error.correlationId").value("client-uuid"));
    }

    @WithMockUser
    @org.testng.annotations.Test
    void validationError_withInvalidHeader_returns400_andGeneratedCorrelationId() throws Exception {
        mockMvc.perform(post("/api/test/validate")
                .header(CorrelationIdFilter.CORRELATION_ID_HEADER, " ")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{}"))
            .andExpect(status().isBadRequest())
            .andExpect(header().exists(CorrelationIdFilter.CORRELATION_ID_HEADER))
            .andExpect(result -> {
                String headerCorrelationId = result.getResponse().getHeader(CorrelationIdFilter.CORRELATION_ID_HEADER);
                Assert.assertNotNull(headerCorrelationId, "X-Correlation-ID response header must be present");

                // Should be generated UUID when client header is invalid.
                UUID.fromString(headerCorrelationId);

                JsonNode root = objectMapper.readTree(result.getResponse().getContentAsString());
                String bodyCorrelationId = root.path("error").path("correlationId").asText();
                Assert.assertNotNull(bodyCorrelationId, "Body correlationId must be present");

                UUID.fromString(bodyCorrelationId);

                Assert.assertEquals(bodyCorrelationId, headerCorrelationId,
                    "Body correlationId does not match response header correlation id");
            });
    }

    @RestController
    @RequestMapping("/api/test")
    static class ValidationController {

        @PostMapping("/validate")
        public void validate(@jakarta.validation.Valid @RequestBody Payload payload) {
            // no-op
        }
    }

    static class Payload {
        @jakarta.validation.constraints.NotBlank
        public String name;
    }
}
