package com.capstone.todo.web.api;

import com.capstone.todo.web.filter.CorrelationIdFilter;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.UUID;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Verifies the standard API error envelope and correlation id behaviour driven by
 * {@link GlobalExceptionHandler} and {@link CorrelationIdFilter}.
 *
 * <p>Uses a standalone MockMvc setup (no Spring Security) to isolate the error-handling
 * behaviour under test, consistent with the lightweight unit-test style used across this module.
 */
public class GlobalExceptionHandlerTest {

    private MockMvc mockMvc;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeMethod
    public void setUp() {
        mockMvc = MockMvcBuilders.standaloneSetup(new ValidationController())
            .setControllerAdvice(new GlobalExceptionHandler())
            .addFilters(new CorrelationIdFilter())
            .build();
    }

    @Test
    public void validationError_withoutHeader_returns400_andGeneratedCorrelationId_andDetails() throws Exception {
        mockMvc.perform(post("/api/test/validate")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{}"))
            .andExpect(status().isBadRequest())
            .andExpect(header().exists(CorrelationIdFilter.CORRELATION_ID_HEADER))
            .andExpect(result -> assertGeneratedCorrelationIdHeaderAndBodyMatch(result))
            .andExpect(jsonPath("$.error.code").value("VALIDATION_ERROR"))
            .andExpect(jsonPath("$.error.details").isArray())
            .andExpect(jsonPath("$.error.correlationId").isNotEmpty());
    }

    @Test
    public void validationError_withHeader_returns400_andSameCorrelationId() throws Exception {
        mockMvc.perform(post("/api/test/validate")
                .header(CorrelationIdFilter.CORRELATION_ID_HEADER, "client-uuid")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{}"))
            .andExpect(status().isBadRequest())
            .andExpect(header().string(CorrelationIdFilter.CORRELATION_ID_HEADER, "client-uuid"))
            .andExpect(jsonPath("$.error.correlationId").value("client-uuid"));
    }

    @Test
    public void validationError_withInvalidHeader_returns400_andGeneratedCorrelationId() throws Exception {
        mockMvc.perform(post("/api/test/validate")
                .header(CorrelationIdFilter.CORRELATION_ID_HEADER, " ")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{}"))
            .andExpect(status().isBadRequest())
            .andExpect(header().exists(CorrelationIdFilter.CORRELATION_ID_HEADER))
            .andExpect(result -> assertGeneratedCorrelationIdHeaderAndBodyMatch(result));
    }

    @Test
    public void validationError_withDisallowedCharactersInHeader_returns400_andGeneratedCorrelationId() throws Exception {
        mockMvc.perform(post("/api/test/validate")
                .header(CorrelationIdFilter.CORRELATION_ID_HEADER, "abc/def")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{}"))
            .andExpect(status().isBadRequest())
            .andExpect(header().exists(CorrelationIdFilter.CORRELATION_ID_HEADER))
            .andExpect(result -> assertGeneratedCorrelationIdHeaderAndBodyMatch(result));
    }

    private void assertGeneratedCorrelationIdHeaderAndBodyMatch(MvcResult result) throws Exception {
        String headerCorrelationId = result.getResponse().getHeader(CorrelationIdFilter.CORRELATION_ID_HEADER);
        Assert.assertNotNull(headerCorrelationId, "X-Correlation-ID response header must be present");

        // Ensure it is UUID-shaped when generated by the server.
        UUID.fromString(headerCorrelationId);

        JsonNode root = objectMapper.readTree(result.getResponse().getContentAsString());
        String bodyCorrelationId = root.path("error").path("correlationId").asText();
        Assert.assertNotNull(bodyCorrelationId, "Body correlationId must be present");

        UUID.fromString(bodyCorrelationId);

        Assert.assertEquals(bodyCorrelationId, headerCorrelationId,
            "Body correlationId does not match response header correlation id");
    }

    @RestController
    @RequestMapping("/api/test")
    static class ValidationController {

        @PostMapping("/validate")
        public void validate(@jakarta.validation.Valid @RequestBody Payload payload) {
            // no-op
        }
    }

    static class Payload {
        @jakarta.validation.constraints.NotBlank
        public String name;
    }
}
